"""<add chat history table>

Revision ID: 22dba7d3b0e5
Revises: b9952348747f
Create Date: 2023-09-30 16:55:01.194430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dba7d3b0e5'
down_revision = 'b9952348747f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.String(length=255), nullable=True),
    sa.Column('bot_response', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_histories_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_courses_lesson_id_lessons', type_='foreignkey')
        batch_op.drop_column('lesson_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_courses_lesson_id_lessons', 'lessons', ['lesson_id'], ['id'])

    op.drop_table('chat_histories')
    # ### end Alembic commands ###
