"""<add homework, learning objs, etc>

Revision ID: 2c466efa16b7
Revises: 22dba7d3b0e5
Create Date: 2023-10-01 19:49:53.399346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c466efa16b7'
down_revision = '22dba7d3b0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_objective1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('learning_objective2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('learning_objective3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('homework1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('homework2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('homework3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('next_course_preview', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('next_course_preview')
        batch_op.drop_column('homework3')
        batch_op.drop_column('homework2')
        batch_op.drop_column('homework1')
        batch_op.drop_column('learning_objective3')
        batch_op.drop_column('learning_objective2')
        batch_op.drop_column('learning_objective1')

    # ### end Alembic commands ###
